exclude: [Gemfile, Gemfile.lock, CNAME, README.md]
name: Desire to Inquire
description: "A blog about one man's quest to become a self-directed learner"
url: http://desiretoinquire.com
sass:
    style: compact
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
