exclude: [Gemfile, Gemfile.lock, CNAME, README.md]
name: Let's Build a Website!
url: http://letsbuilda.website
sass:
    style: compact
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
